### ISSUE TITLE
Local host connection refused

### ISSUE THREAD

**Issue by NI-CE1** [nihanth777/embedded#5]
port 127.0.0.1 is wrong.

**Comment by bannersb19** [comment]
![localhost_port_3000 not working](https://user-images.githubusercontent.com/86323992/235174076-200580a2-8b51-426b-98d4-3586ff061f56.PNG)
npm start command failing to start my react app.

**Comment by bigzen** [comment]
> port 127.0.0.1 is wrong.

change it to visible IP address of local host to get it working
